name: "Podcast Generator"
author: "Sandesh"
description: "Generates a feed for a podcast from a YAML file"

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
  description: The commiter email address
  required: True
  default: ${{ github.actor }}@localhost
name:
  description: The committer's name
  required: True
  default: ${{ github.actor }}